trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
  inputs:
    terraformVersion: '0.12.12'
  displayName: Install Terraform

- task: TerraformTaskV1@0
  displayName: Terraform Init
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: terraform
    backendServiceArm: 'k8sdeploy'

- task: TerraformTaskV1@0
  displayName: Terraform Plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: terraform
    environmentServiceNameAzureRM: 'k8sdeploy'

# - task: TerraformTaskV1@0
#   displayName: Terraform Apply
#   inputs:
#     provider: 'azurerm'
#     command: 'apply'
#     workingDirectory: terraform
#     environmentServiceNameAzureRM: 'k8sdeploy'